version = 0.1
[default.deploy.parameters]
stack_name = "kbv-hmrc"
resolve_s3 = true
s3_prefix = "kbv-hmrc"
region = "eu-west-2"
capabilities = "CAPABILITY_IAM"
image_repositories = []
parameter_overrides = [
    "BearerTokenName=HMRCBearerToken",
    "Environment=dev",
    "CommonStackName=common-cri-api"
]
