AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: "Digital Identity IPV CRI KBV HMRC API"

Globals:
  Function:
    Runtime: nodejs18.x
    Architectures:
      - arm64
    Timeout: 3

Resources:
  FetchQuestionsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../lambdas/fetch-questions
      Handler: fetch-questions-handler.lambdaHandler
      FunctionUrlConfig:
        AuthType: AWS_IAM
        Cors:
          AllowOrigins: ["*"]
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints:
          - src/fetch-questions-handler.ts

Outputs:
  FetchQuestionsFunctionURLEndpoint:
    Description: FURLFunction function name
    Value: !GetAtt FetchQuestionsFunctionUrl.FunctionUrl
  FetchQuestionsFunction:
    Description: "FetchQuestions Lambda Function ARN"
    Value: !GetAtt FetchQuestionsFunction.Arn
  FetchQuestionsFunctionIamRole:
    Description: "Implicit IAM Role created for FetchQuestions function"
    Value: !GetAtt FetchQuestionsFunctionRole.Arn

