AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: "Digital Identity IPV CRI KBV HMRC API"

Parameters:
  BearerTokenName:
    Type: String

Globals:
  Function:
    Runtime: nodejs18.x
    Architectures:
      - arm64
    Timeout: 3

Resources:
  ExecuteStateMachineFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../lambdas/execute-state-machine
      Handler: execute-state-machine-handler.lambdaHandler
      Timeout: 60
      FunctionUrlConfig:
        AuthType: AWS_IAM
        Cors:
          AllowOrigins: ["*"]
      Policies:
        - Statement:
            Effect: Allow
            Action:
              - states:StartSyncExecution
            Resource:
              - !Sub arn:aws:states:${AWS::Region}:${AWS::AccountId}:stateMachine:${GetIvqQuestionsStateMachine}
        - Statement:
            Effect: Allow
            Action:
              - states:DescribeExecution
              - states:StopExecution
            Resource:
              - !Sub arn:aws:states:${AWS::Region}:${AWS::AccountId}:execution:${GetIvqQuestionsStateMachine}:*
        - Statement:
            - Effect: Allow
              Action:
                - events:PutTargets
                - events:PutRule
                - events:DescribeRule
              Resource:
                - "*"

    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints:
          - src/execute-state-machine-handler.ts

  SubmitAnswerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../lambdas/submit-answer
      Handler: submit-answer-handler.lambdaHandler
      FunctionUrlConfig:
        AuthType: AWS_IAM
        Cors:
          AllowOrigins: ["*"]
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints:
          - src/submit-answer-handler.ts

  FetchQuestionsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../lambdas/fetch-questions
      Handler: fetch-questions-handler.lambdaHandler
      FunctionUrlConfig:
        AuthType: AWS_IAM
        Cors:
          AllowOrigins: ["*"]
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints:
          - src/fetch-questions-handler.ts

  UserAgent:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub "/${AWS::StackName}/UserAgent"
      Value: govuk-one-login
      Type: String
      Description: User agent for HMRC requests

  QuestionsUrl:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub "/${AWS::StackName}/QuestionsUrl"
      Value: https://test-api.service.hmrc.gov.uk/individuals/verification/identity-verification-questions/questions
      Type: String
      Description: URL for HMRC /questions endpoint

  AnswersUrl:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub "/${AWS::StackName}/AnswersUrl"
      Value: https://test-api.service.hmrc.gov.uk/individuals/verification/identity-verification-questions/answers
      Type: String
      Description: URL for HMRC /answers endpoint

  QuestionsTable:
    Type: "AWS::DynamoDB::Table"
    Properties:
      TableName: !Sub "${AWS::StackName}-questions"
      BillingMode: "PAY_PER_REQUEST"
      AttributeDefinitions:
        - AttributeName: "sessionId"
          AttributeType: "S"
        - AttributeName: "questionKey"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "sessionId"
          KeyType: "HASH"
        - AttributeName: "questionKey"
          KeyType: "RANGE"

  GetIvqQuestionsStateMachine:
    Type: AWS::Serverless::StateMachine
    Properties:
      DefinitionUri: ../step-functions/get-ivq-questions.asl.json
      Type: EXPRESS
      DefinitionSubstitutions:
        QuestionsTableName: !Ref QuestionsTable
        QuestionsUrl: !Ref QuestionsUrl
        UserAgent: !Ref UserAgent
        FetchQuestionsArn: !GetAtt FetchQuestionsFunction.Arn
        BearerTokenName: !Ref BearerTokenName
      Name: !Sub "${AWS::StackName}-GetIvqQuestions"
      Logging:
        Destinations:
          - CloudWatchLogsLogGroup:
              LogGroupArn: !GetAtt GetIvqQuestionsStateMachineLogGroup.Arn
        IncludeExecutionData: True
        Level: ALL
      Policies:
        - DynamoDBWritePolicy:
            TableName: !Ref QuestionsTable
        - DynamoDBReadPolicy:
            TableName: !Ref QuestionsTable
        - AWSSecretsManagerGetSecretValuePolicy:
            SecretArn: !Sub arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:${BearerTokenName}-??????
        - LambdaInvokePolicy:
            FunctionName: !Ref FetchQuestionsFunction
        - Statement:
            Effect: Allow
            Action:
              - ssm:GetParameters
              - ssm:GetParameter
            Resource:
              - !Sub "arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/${AWS::StackName}/QuestionsUrl"
              - !Sub "arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/${AWS::StackName}/UserAgent"
        - Statement:
            Effect: Allow
            Action:
              - logs:*
            Resource:
              - "*"

  GetIvqQuestionsStateMachineLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/apigateway/${AWS::StackName}-${PrivateNinoCheckApi}-GetIvqQuestions-logs
      RetentionInDays: 365

  GetQuestionStateMachine:
    Type: AWS::Serverless::StateMachine
    Properties:
      DefinitionUri: ../step-functions/get-question.asl.json
      Type: EXPRESS
      Name: !Sub "${AWS::StackName}-GetQuestion"
      Logging:
        Destinations:
          - CloudWatchLogsLogGroup:
              LogGroupArn: !GetAtt GetQuestionStateMachineLogGroup.Arn
        IncludeExecutionData: True
        Level: ALL
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref QuestionsTable
        - StepFunctionsExecutionPolicy:
            StateMachineName: !GetAtt GetIvqQuestionsStateMachine.Name
        - LambdaInvokePolicy:
            FunctionName: !Ref ExecuteStateMachineFunction
        - Statement:
            Effect: Allow
            Action:
              - logs:*
            Resource:
              - "*"
      DefinitionSubstitutions:
        ExecuteStateMachineFunctionName: !Ref ExecuteStateMachineFunction
        QuestionsTableName: !Ref "QuestionsTable"
        GetIvqQuestionsStateMachineArn: !GetAtt GetIvqQuestionsStateMachine.Arn

  GetQuestionStateMachineLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/apigateway/${AWS::StackName}-${PrivateNinoCheckApi}-GetQuestion-logs
      RetentionInDays: 365

  PostAnswerStateMachine:
    Type: AWS::Serverless::StateMachine
    Properties:
      DefinitionUri: ../step-functions/post-answer.asl.json
      Name: !Sub "${AWS::StackName}-PostAnswer"
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref QuestionsTable
        - DynamoDBWritePolicy:
            TableName: !Ref QuestionsTable
        - StepFunctionsExecutionPolicy:
            StateMachineName: !GetAtt PostIVQAnswersStateMachine.Name
      DefinitionSubstitutions:
        AnswersIVQStateMachine: !Ref "PostIVQAnswersStateMachine"
        QuestionsTableName: !Ref "QuestionsTable"

  PostIVQAnswersStateMachine:
    Type: AWS::Serverless::StateMachine
    Properties:
      DefinitionUri: ../step-functions/post-ivq-answers.asl.json
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref QuestionsTable
        - AWSSecretsManagerGetSecretValuePolicy:
            SecretArn: !Sub "arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:${BearerTokenName}-??????"
        - SSMParameterWithSlashPrefixReadPolicy:
            ParameterName: !Ref AnswersUrl
        - SSMParameterWithSlashPrefixReadPolicy:
            ParameterName: !Ref UserAgent
        - LambdaInvokePolicy:
            FunctionName: !Ref SubmitAnswerFunction
      Name: !Sub "${AWS::StackName}-PostIVQAnswers"
      DefinitionSubstitutions:
        BearerTokenName: !Ref BearerTokenName
        AnswersUrlName: !Ref AnswersUrl
        UserAgentName: !Ref UserAgent
        PostIVQAnswersLambdaArn: !GetAtt SubmitAnswerFunction.Arn
        QuestionsTableName: !Ref QuestionsTable

Outputs:
  ExecuteStateMachineFunctionURLEndpoint:
    Description: FURLFunction function name
    Value: !GetAtt ExecuteStateMachineFunctionUrl.FunctionUrl
  ExecuteStateMachineFunction:
    Description: "ExecuteStateMachine Lambda Function ARN"
    Value: !GetAtt ExecuteStateMachineFunction.Arn
  ExecuteStateMachineFunctionIamRole:
    Description: "Implicit IAM Role created for ExecuteStateMachine function"
    Value: !GetAtt ExecuteStateMachineFunctionRole.Arn

  SubmitAnswerFunctionURLEndpoint:
    Description: FURLFunction function name
    Value: !GetAtt SubmitAnswerFunctionUrl.FunctionUrl
  SubmitAnswerFunction:
    Description: "SubmitAnswer Lambda Function ARN"
    Value: !GetAtt SubmitAnswerFunction.Arn
  SubmitAnswerFunctionIamRole:
    Description: "Implicit IAM Role created for SubmitAnswer function"
    Value: !GetAtt SubmitAnswerFunctionRole.Arn

  FetchQuestionsFunctionURLEndpoint:
    Description: FURLFunction function name
    Value: !GetAtt FetchQuestionsFunctionUrl.FunctionUrl
  FetchQuestionsFunction:
    Description: "FetchQuestions Lambda Function ARN"
    Value: !GetAtt FetchQuestionsFunction.Arn
  FetchQuestionsFunctionIamRole:
    Description: "Implicit IAM Role created for FetchQuestions function"
    Value: !GetAtt FetchQuestionsFunctionRole.Arn
