name: Check PR

on: pull_request
permissions: {}

jobs:
  pre-commit:
    name: pre-commit
    runs-on: ubuntu-latest
    concurrency:
      group: pre-commit-${{ github.head_ref || github.ref_name }}
      cancel-in-progress: true
    steps:
      - name: Run pre-commit
        uses: govuk-one-login/github-actions/code-quality/run-pre-commit@cd7d35dde348251237efbbaee5345e95adef0321
        with:
          all-files: true

  unit-tests:
    name: Run tests
    uses: ./.github/workflows/run-unit-tests.yml

  mocked-tests:
    name: Run tests
    uses: ./.github/workflows/run-mocked-tests.yml

  pre-merge-integration-tests:
    name: Run pre-merge integration tests
    uses: ./.github/workflows/run-pre-merge-integration-tests.yml
    secrets:
      PREMERGE_PARAMETER_PREFIX_STACK_NAME: "kbv-hmrc-cri-api"
      API_KEY_DEV: "NOT_USED_CURRENTLY"
      CORE_STUB_URL: ${{ secrets.CORE_STUB_URL }}
      CORE_STUB_USERNAME: ${{ secrets.CORE_STUB_USERNAME }}
      CORE_STUB_PASSWORD: ${{ secrets.CORE_STUB_PASSWORD }}
      ORCHESTRATOR_STUB_URL: ${{ secrets.ORCHESTRATOR_STUB_URL }}

    permissions:
      id-token: write
      contents: read

  deploy-preview-stack:
    name: Preview Stack Deployment
    needs: pre-merge-integration-tests
    uses: ./.github/workflows/deploy-branch.yml
    permissions:
      id-token: write
      contents: read

  aws-tests:
    name: Run tests
    needs: deploy-preview-stack
    uses: ./.github/workflows/run-aws-tests.yml
    permissions:
      id-token: write
      contents: read
    with:
      stack-name: ${{ needs.deploy-preview-stack.outputs.stack-name }}
      aws-region: ${{ needs.deploy-preview-stack.outputs.aws-region }}
