name: Preview

on:
  workflow_dispatch:
  workflow_call:
    outputs:
      stack-name:
        description: The deployed stack name
        value: ${{ jobs.deploy.outputs.stack-name }}
      aws-region:
        description: The region in which the stack was deployed
        value: ${{ jobs.deploy.outputs.aws-region }}

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: {}
    timeout-minutes: 15
    concurrency:
      group: build-development-${{ github.head_ref || github.ref_name }}
    outputs:
      sha_short: ${{ steps.vars.outputs.sha_short }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Get stack name vars
        id: vars
        run: |
          echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      - name: Build SAM application
        uses: govuk-one-login/github-actions/sam/build-application@main
        id: build
        with:
          template: infrastructure/template.yaml
          cache-name: ipv-cri-hmrc-kbv-api-${{ steps.vars.outputs.sha_short }}
          pull-repository: true

  deploy:
    name: Deploy stack
    runs-on: ubuntu-latest
    timeout-minutes: 15
    needs: build
    concurrency:
      group: deploy-development-${{ github.head_ref || github.ref_name }}
    environment:
      name: development
      url: ${{ steps.deploy.outputs.stack-url }}
    outputs:
      aws-region: ${{ steps.deploy.outputs.aws-region }}
      stack-name: ${{ steps.deploy.outputs.stack-name }}
    steps:
      - name: Deploy stack
        uses: govuk-one-login/github-actions/sam/deploy-stack@main
        id: deploy
        with:
          sam-deployment-bucket: ${{ vars.DEPLOYMENT_ARTIFACTS_BUCKET }}
          aws-role-arn: ${{ vars.DEPLOYMENT_ROLE_ARN }}
          stack-name-prefix: preview-kbv-hmrc-api
          cache-name: ipv-cri-hmrc-kbv-api-${{ needs.build.outputs.sha_short}}
          s3-prefix: preview
          pull-repository: true
          delete-failed-stack: true
          tags: |
            cri:component=ipv-cri-kbv-hmrc-api
            cri:stack-type=preview
            cri:application=Lime
            cri:deployment-source=github-actions
          parameters: |
            DeploymentType=pre-merge-integration
            UseApiKey=" "
            ParameterPrefix=kbv-hmrc-cri-api
            Environment=dev
            CommonStackName=hmrc-kbv-common-cri-api-local
