name: Preview

on:
  workflow_dispatch:
  workflow_call:
    outputs:
      stack-name:
        description: The deployed stack name
        value: ${{ jobs.deploy.outputs.stack-name }}
      aws-region:
        description: The region in which the stack was deployed
        value: ${{ jobs.deploy.outputs.aws-region }}

permissions:
  id-token: write
  contents: read

jobs:
  build:
    name: Build SAM app
    runs-on: ubuntu-latest
    permissions: {}
    outputs:
      artifact-name: ${{ steps.build.outputs.artifact-name }}
    steps:
      - name: Build SAM application
        uses: govuk-one-login/github-actions/sam/build-application@d233e5a687f5c816b19bb25991d5709658b29ebc
        id: build
        with:
          template: infrastructure/template.yaml
          artifact-name: kbv-hmrc-api
          cache-key: kbv-hmrc-api
          pull-repository: true

  deploy:
    name: Deploy stack
    runs-on: ubuntu-latest
    timeout-minutes: 15
    needs: build
    concurrency:
      group: deploy-development-${{ github.head_ref || github.ref_name }}
    environment:
      name: development
      url: ${{ steps.deploy.outputs.stack-url }}
    outputs:
      aws-region: ${{ steps.deploy.outputs.aws-region }}
      stack-name: ${{ steps.deploy.outputs.stack-name }}
    steps:
      - name: Deploy stack
        uses: govuk-one-login/github-actions/sam/deploy-stack@d233e5a687f5c816b19bb25991d5709658b29ebc
        id: deploy
        with:
          sam-deployment-bucket: ${{ vars.DEPLOYMENT_ARTIFACTS_BUCKET }}
          aws-role-arn: ${{ vars.DEPLOYMENT_ROLE_ARN }}
          stack-name-prefix: preview-kbv-hmrc-api
          s3-prefix: preview
          pull-repository: true
          delete-failed-stack: true
          artifact-path: .aws-sam/build
          artifact-name: ${{ needs.build.outputs.artifact-name }}
          tags: |
            cri:component=kbv-hmrc-api
            cri:stack-type=preview
            cri:application=Orange
            cri:deployment-source=github-actions
          parameters: |
            Environment=dev
